Repository AM-Inspire-Devfit/devfit-server, pull requests merged in 2025-04, with the labels that each got.

#158 refactor: project 삭제 uri 수정
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
Labels: ♻️ refactor

#160 refactor: 프로젝트 기본 정보 수정 Request Dto에서 goal 필드 제거
  src/main/java/com/amcamp/domain/project/dto/request/ProjectBasicInfoUpdateRequest.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#155 feat: 스프린트 & 태스크 조회 기능 구현
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintDetailResponse.java
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskBasicInfoResponse.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: ✨ feature

#164 fix: 팀 정보 수정 메소드 수정
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/domain/Team.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamEmojiUpdateRequest.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamUpdateRequest.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: 🐛 bug/error

#169 fix: 스프린트 페이징 방향 처리 누락으로 인한 목록 조회 오류 수정
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintPagingDirection.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: 🐛 bug/error

#161 refactor: Docker 네트워크 모드 bridge로 변경
  docker-compose.yml
  nginx/default.conf
Labels: ♻️ refactor

#171 fix: Docker bridge 네트워크 전환 후 Nginx 502 에러 수정
  docker-compose.yml
  nginx/default.conf
Labels: 🐛 bug/error

#176 fix: 태스크 진행상태별 수정 삭제 권한 부여
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error

#167 chore: Swagger 보안 설정
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#178 fix: 태스크 sos 후 본인 할당 문제 수정
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error

#182 feat: 운영 환경 구성
  .github/workflows/production_build_deploy.yml
  src/main/java/com/amcamp/global/common/constants/UrlConstants.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
  src/main/java/com/amcamp/global/helper/SpringEnvironmentHelper.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ feature

#184 refactor: 개발 및 운영 환경에서 쿠키 설정 변경
  src/main/java/com/amcamp/global/util/CookieUtil.java
Labels: ♻️ refactor

#191 refactor: 프로젝트 참여자 나간 상태를 UNKNOWN 처리 방식에서 참여 상태로 관리하도록 개선
  src/main/java/com/amcamp/domain/contribution/dto/response/ContributionInfoResponse.java
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipantStatus.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipantUnknown.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantInfoResponse.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepositoryImpl.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ♻️ refactor

#195 fix: 스프린트 내 태스크가 조회되지 않을 경우 예외 처리 & 팀/프로젝트/태스크 명 글자수 제한
  src/main/java/com/amcamp/domain/contribution/dto/response/BasicContributionInfoResponse.java
  src/main/java/com/amcamp/domain/contribution/dto/response/ContributionInfoResponse.java
  src/main/java/com/amcamp/domain/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/amcamp/domain/meeting/dto/request/MeetingTitleUpdateRequest.java
  src/main/java/com/amcamp/domain/member/dto/request/NicknameUpdateRequest.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectUpdateRequest.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepositoryCustom.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepositoryImpl.java
  src/main/java/com/amcamp/domain/task/dto/request/TaskBasicInfoUpdateRequest.java
  src/main/java/com/amcamp/domain/task/dto/request/TaskCreateRequest.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamUpdateRequest.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error

#197 refactor: ProjectAdmin 변경 로직 요청 파라미터 수정
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
Labels: ♻️ refactor

#203 refactor: Project 가입 신청 시 status inactive 인 경우 요청 보내기 허용
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
Labels: ♻️ refactor

#205 refactor: projectRegistration 생성 시 팀 전체-> 프로젝트 해당하는 요청만 검증하도록 오류 수정
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java
Labels: ♻️ refactor

#209 fix: 프로젝트 참가 칼럼명 수정
  src/main/java/com/amcamp/domain/project/domain/ProjectRegistration.java
Labels: 🐛 bug/error

#211 feat: 프로젝트별 스프린트 아이디 목록 조회 기능
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintIdResponse.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: ✨ feature

#214 refactor: Project 가입 신청 취소 필요 파라미터 수정
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#215 refactor: Project 가입신청 api 요청 파라미터 수정
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
Labels: ♻️ refactor

#218 feat: 스프린트별 참가자 목록 & 동료 평가 여부 반환 메소드
  src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryCustom.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantFeedbackInfoResponse.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
Labels: ✨ feature

#217 fix: OpenAI 피드백 메시지 프롬프트 수정
  src/main/java/com/amcamp/domain/feedback/dto/request/ChatRequest.java
Labels: 🐛 bug/error

#221 fix: prod 환경에서 profile group 누락으로 설정 미적용 수정
  src/main/resources/application.yml
Labels: 🐛 bug/error

#225 fix: meeting status enum 설정
  src/main/java/com/amcamp/domain/meeting/domain/Meeting.java
Labels: 🐛 bug/error

#229 fix: prod 환경 쿠키 SameSite 값을 None으로 수정
  src/main/java/com/amcamp/global/util/CookieUtil.java
Labels: 🐛 bug/error

#230 fix: task status 완료 시 완료 날짜 업데이트 수정
  src/main/java/com/amcamp/domain/task/domain/Task.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error
