Repository AM-Inspire-Devfit/devfit-server, pull requests merged in 2025-03, with the labels that each got.

#78 feat: 팀에 속한 회원 이미지, 회원 목록, 팀장 조회
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/main/java/com/amcamp/domain/member/dao/MemberRepository.java
  src/main/java/com/amcamp/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/amcamp/domain/member/dao/MemberRepositoryImpl.java
  src/main/java/com/amcamp/domain/member/dto/response/BasicMemberResponse.java
  src/main/java/com/amcamp/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/dao/TeamParticipantRepository.java
  src/main/java/com/amcamp/domain/team/dto/response/TeamAdminResponse.java
  src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: ✨ feature

#83 feat: 스프린트 생성 기능 구현
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: ✨ feature

#89 refactor: Swagger API 목록 정렬
  src/main/java/com/amcamp/domain/auth/api/AuthController.java
  src/main/java/com/amcamp/domain/image/api/ImageController.java
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/resources/application.yml
Labels: ♻️ refactor

#86 feat: 스프린트 수정, 삭제 기능 구현
  src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintBasicUpdateRequest.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintToDoUpdateRequest.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
Labels: ✨ feature

#93 refactor: 예외 응답에서 field 및 given 제거
  src/main/java/com/amcamp/global/exception/CommonException.java
  src/main/java/com/amcamp/global/exception/ErrorDetail.java
  src/main/java/com/amcamp/global/exception/ErrorMsg.java
  src/main/java/com/amcamp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/amcamp/global/exception/errorcode/AuthErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/BaseErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/ImageErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/MemberErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java
  src/test/java/com/amcamp/global/exception/ExceptionHandlerTest.java
Labels: ♻️ refactor

#95 refactor: 스프린트 제목에 번호가 자동으로 지정되도록 변경
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintBasicUpdateRequest.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java
Labels: ♻️ refactor

#96 feat: Task 생성, 수정, 삭제 기능 구현
  src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepository.java
  src/main/java/com/amcamp/domain/task/domain/Task.java
  src/main/java/com/amcamp/domain/task/dto/request/TaskBasicInfoUpdateRequest.java
  src/main/java/com/amcamp/domain/task/dto/request/TaskCreateRequest.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ✨ feature

#104 feat: sos 기능 구현 & 관련 태스크 메소드 수정
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/domain/task/domain/SOSStatus.java
  src/main/java/com/amcamp/domain/task/domain/Task.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ✨ feature

#101 feat: 프로젝트 삭제/나가기 구현
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectParticipantRepository.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipantRole.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectAdminChangeRequest.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ✨ feature

#106 feat: 프로젝트별 스프린트 목록 조회
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: ✨ feature

#109 feat: OpenAI 기반 피드백 메시지 개선
  src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java
  src/main/java/com/amcamp/domain/feedback/application/ChatGptService.java
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/domain/feedback/dto/Choice.java
  src/main/java/com/amcamp/domain/feedback/dto/Message.java
  src/main/java/com/amcamp/domain/feedback/dto/request/ChatRequest.java
  src/main/java/com/amcamp/domain/feedback/dto/request/OriginalFeedbackRequest.java
  src/main/java/com/amcamp/domain/feedback/dto/response/ChatResponse.java
  src/main/java/com/amcamp/domain/feedback/dto/response/FeedbackRefineResponse.java
  src/main/java/com/amcamp/global/config/feign/FeignConfig.java
  src/main/java/com/amcamp/infra/config/feign/OpenAiClient.java
  src/main/java/com/amcamp/infra/config/openai/OpenAiProperties.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/resources/application-openai.yml
  src/main/resources/application.yml
Labels: ✨ feature

#108 feat: 프로젝트 가입/참여자 조회 구현
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java
  src/main/java/com/amcamp/domain/project/domain/Project.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipantUnknown.java
  src/main/java/com/amcamp/domain/project/domain/ProjectRegistration.java
  src/main/java/com/amcamp/domain/project/domain/ProjectRegistrationStatus.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectInfoResponse.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantInfoResponse.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectRegistrationInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ✨ feature

#114 feat: 피드백 메시지 전송 기능 구현
  src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepository.java
  src/main/java/com/amcamp/domain/feedback/domain/Feedback.java
  src/main/java/com/amcamp/domain/feedback/dto/request/FeedbackSendRequest.java
  src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
Labels: ✨ feature

#105 refactor: 프로젝트 목록 조회 QueryDSL 적용
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepository.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustomImpl.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectRegistrationInfoResponse.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#117 feat: 팀 미팅 생성 구현
  src/main/java/com/amcamp/domain/meeting/api/MeetingController.java
  src/main/java/com/amcamp/domain/meeting/application/MeetingService.java
  src/main/java/com/amcamp/domain/meeting/dao/MeetingRepository.java
  src/main/java/com/amcamp/domain/meeting/domain/Meeting.java
  src/main/java/com/amcamp/domain/meeting/domain/MeetingStatus.java
  src/main/java/com/amcamp/domain/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/global/exception/errorcode/MeetingErrorCode.java
  src/test/java/com/amcamp/domain/meeting/MeetingServiceTest.java
Labels: ✨ feature

#116 feat: 피드백 메시지 조회 기능 구현
  src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepository.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryCustom.java
  src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryImpl.java
  src/main/java/com/amcamp/domain/feedback/domain/Feedback.java
  src/main/java/com/amcamp/domain/feedback/dto/response/FeedbackInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
Labels: ✨ feature

#107 feat: 스프린트별 태스크 목록 조회 · 회원이 담당하고 있는 태스크 목록 조회 기능 구현
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepository.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepositoryCustom.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepositoryImpl.java
  src/main/java/com/amcamp/domain/task/domain/Task.java
  src/main/java/com/amcamp/domain/task/domain/TaskStatus.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ✨ feature

#125 refactor: 프로젝트 참가자 응답 필드 수정
  src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantInfoResponse.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#112 feat: 기여도 · 진척도 조회 기능 구현
  src/main/java/com/amcamp/domain/contribution/api/ContributionController.java
  src/main/java/com/amcamp/domain/contribution/application/ContributionService.java
  src/main/java/com/amcamp/domain/contribution/dao/ContributionRepository.java
  src/main/java/com/amcamp/domain/contribution/domain/Contribution.java
  src/main/java/com/amcamp/domain/contribution/dto/response/BasicContributionInfoResponse.java
  src/main/java/com/amcamp/domain/contribution/dto/response/ContributionInfoResponse.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/domain/SprintContribution.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintProgressResponse.java
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/application/TaskService.java
  src/main/java/com/amcamp/domain/task/dao/TaskRepository.java
  src/main/java/com/amcamp/global/exception/errorcode/ContributionErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ✨ feature

#128 refactor: 프로젝트, 스프린트 생성 시 시작 날짜를 현재 날짜로 설정되도록 변경
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/domain/Project.java
  src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/amcamp/domain/project/dto/request/ProjectTodoInfoUpdateRequest.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java
  src/main/java/com/amcamp/domain/sprint/dto/request/SprintToDoUpdateRequest.java
  src/main/java/com/amcamp/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
  src/test/java/com/amcamp/domain/meeting/MeetingServiceTest.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: ♻️ refactor

#123 feat: 팀 미팅 수정/조회/삭제
  src/main/java/com/amcamp/domain/meeting/api/MeetingController.java
  src/main/java/com/amcamp/domain/meeting/application/MeetingService.java
  src/main/java/com/amcamp/domain/meeting/dao/MeetingRepository.java
  src/main/java/com/amcamp/domain/meeting/dao/MeetingRepositoryCustom.java
  src/main/java/com/amcamp/domain/meeting/dao/MeetingRepositoryImpl.java
  src/main/java/com/amcamp/domain/meeting/domain/Meeting.java
  src/main/java/com/amcamp/domain/meeting/dto/request/MeetingDtUpdateRequest.java
  src/main/java/com/amcamp/domain/meeting/dto/request/MeetingTitleUpdateRequest.java
  src/main/java/com/amcamp/domain/meeting/dto/response/MeetingInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/MeetingErrorCode.java
  src/main/java/com/amcamp/infra/scheduler/MeetingStatusScheduler.java
  src/test/java/com/amcamp/domain/meeting/MeetingServiceTest.java
Labels: ✨ feature

#133 refactor: 프로젝트 목록 조회 시 Admin 표시
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#131 fix: 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되는 문제 수정
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error

#126 refactor: 프로젝트 참가자 목록 조회 API 페이지네이션 적용
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#137 fix: 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되는 문제 수정
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
  src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Labels: 🐛 bug/error

#132 feat: 회원별 프로젝트 내 스프린트 목록 조회 기능 구현
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintProgressResponse.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: ✨ feature

#138 chore: Nginx 리버스 프록시 도입 및 HTTPS 적용
  .github/workflows/develop_build_deploy.yml
  docker-compose.yml
  nginx/default.conf
  src/main/java/com/amcamp/global/common/constants/UrlConstants.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
Labels: ⚙️ chore

#142 refactor: 프로젝트 목록 조회 시 Admin 표시
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ♻️ refactor

#144 chore: SpringEnvironmentHelper 도입
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
  src/main/java/com/amcamp/global/helper/SpringEnvironmentHelper.java
Labels: ⚙️ chore

#146 feat: 프로젝트 가입 신청 목록 조회 시 request의 닉네임과 프로필 함께 조회
  src/main/java/com/amcamp/domain/project/api/ProjectController.java
  src/main/java/com/amcamp/domain/project/application/ProjectService.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryCustom.java
  src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryImpl.java
  src/main/java/com/amcamp/domain/project/dto/response/ProjectRegisterDetailResponse.java
  src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Labels: ✨ feature

#148 chore: 개발 환경 ddl-auto 설정 변경
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/resources/application-dev.yml
Labels: ⚙️ chore

#150 fix: 프로젝트에서 나간 사용자(Unknown)에게 피드백 전송이 불가능하도록 수정
  src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java
  src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
Labels: 🐛 bug/error

#153 fix: 스프린트 수정 시 마감일을 다음 스프린트 시작일 이후로 설정할 수 없도록 수정
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java
  src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: 🐛 bug/error

#152 feat: 스프린트와 태스크 조회 기능 구현
  src/main/java/com/amcamp/domain/sprint/api/SprintController.java
  src/main/java/com/amcamp/domain/sprint/application/SprintService.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java
  src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java
  src/main/java/com/amcamp/domain/sprint/dto/response/SprintDetailResponse.java
  src/main/java/com/amcamp/domain/task/api/TaskController.java
  src/main/java/com/amcamp/domain/task/dto/response/TaskBasicInfoResponse.java
  src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
Labels: ✨ feature
