Repository AM-Inspire-Devfit/devfit-server, pull requests merged in 2025-02, with the labels that each got.

#26 feat: 소셜 로그인 구현
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_pull_request.yml
  build.gradle
  src/main/java/com/amcamp/domain/HealthController.java
  src/main/java/com/amcamp/domain/auth/api/AuthController.java
  src/main/java/com/amcamp/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/domain/auth/application/GoogleService.java
  src/main/java/com/amcamp/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/amcamp/domain/auth/application/JwtTokenService.java
  src/main/java/com/amcamp/domain/auth/application/KakaoService.java
  src/main/java/com/amcamp/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/amcamp/domain/auth/domain/OauthProvider.java
  src/main/java/com/amcamp/domain/auth/domain/RefreshToken.java
  src/main/java/com/amcamp/domain/auth/dto/AccessTokenDto.java
  src/main/java/com/amcamp/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/amcamp/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/amcamp/domain/auth/dto/response/IdTokenResponse.java
  src/main/java/com/amcamp/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/amcamp/domain/member/api/.gitkeep
  src/main/java/com/amcamp/domain/member/application/.gitkeep
  src/main/java/com/amcamp/domain/member/dao/MemberRepository.java
  src/main/java/com/amcamp/domain/member/domain/Member.java
  src/main/java/com/amcamp/domain/member/domain/MemberRole.java
  src/main/java/com/amcamp/domain/member/domain/MemberStatus.java
  src/main/java/com/amcamp/domain/member/domain/OauthInfo.java
  src/main/java/com/amcamp/domain/member/dto/.gitkeep
  src/main/java/com/amcamp/global/common/constants/SecurityConstants.java
  src/main/java/com/amcamp/global/common/exception/auth/AuthErrorCode.java
  src/main/java/com/amcamp/global/common/exception/auth/AuthException.java
  src/main/java/com/amcamp/global/config/feign/FeignConfig.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
  src/main/java/com/amcamp/global/util/CookieUtil.java
  src/main/java/com/amcamp/global/util/JwtUtil.java
  src/main/java/com/amcamp/infra/config/feign/GoogleOauthClient.java
  src/main/java/com/amcamp/infra/config/feign/KakaoOauthClient.java
  src/main/java/com/amcamp/infra/config/jwt/JwtProperties.java
  src/main/java/com/amcamp/infra/config/oauth/GoogleProperties.java
  src/main/java/com/amcamp/infra/config/oauth/KakaoProperties.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/amcamp/exception/AuthExceptionHandlerTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#34 chore: 로그인한 멤버 조회 유틸리티 구현
  src/main/java/com/amcamp/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/amcamp/global/common/exception/AuthException.java
  src/main/java/com/amcamp/global/common/exception/GlobalExceptionManager.java
  src/main/java/com/amcamp/global/common/response/CommonResponse.java
  src/main/java/com/amcamp/global/common/response/CommonResponseAdvice.java
  src/main/java/com/amcamp/global/exception/CommonException.java
  src/main/java/com/amcamp/global/exception/ErrorDetail.java
  src/main/java/com/amcamp/global/exception/ErrorMsg.java
  src/main/java/com/amcamp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/amcamp/global/exception/errorcode/AuthErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/BaseErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/MemberErrorCode.java
  src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
  src/main/java/com/amcamp/global/security/PrincipalDetails.java
  src/main/java/com/amcamp/global/util/MemberUtil.java
  src/test/java/com/amcamp/global/exception/ExceptionHandlerTest.java
  src/test/java/com/amcamp/global/util/MemberUtilTest.java
Labels: ✨ feature

#36 feat: Swagger UI에 Authorization 헤더 추가
  src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
Labels: ✨ feature

#38 fix: Docker Container Timezone 설정
  docker-compose.yml
Labels: 🐛 bug/error

#42 chore: Querydsl 설정
  build.gradle
  src/main/java/com/amcamp/global/config/querydsl/QueryDslConfig.java
Labels: ⚙️ chore

#44 feat: 팀 생성 및 참여 구현
  src/main/java/com/amcamp/domain/participant/dao/ParticipantRepository.java
  src/main/java/com/amcamp/domain/participant/domain/Participant.java
  src/main/java/com/amcamp/domain/participant/domain/ParticipantRole.java
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/dao/TeamRepository.java
  src/main/java/com/amcamp/domain/team/domain/Team.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamInviteCodeRequest.java
  src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java
  src/main/java/com/amcamp/domain/team/dto/response/TeamInviteCodeResponse.java
  src/main/java/com/amcamp/global/common/constants/RedisConstants.java
  src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java
  src/main/java/com/amcamp/global/util/RandomUtil.java
  src/main/java/com/amcamp/global/util/RedisUtil.java
  src/main/java/com/amcamp/infra/config/redis/RedisConfig.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: ✨ feature

#47 feat: 회원 프로필 이미지 및 닉네임 변경 기능 구현
  build.gradle
  src/main/java/com/amcamp/domain/image/api/ImageController.java
  src/main/java/com/amcamp/domain/image/application/ImageService.java
  src/main/java/com/amcamp/domain/image/dao/ImageRepository.java
  src/main/java/com/amcamp/domain/image/domain/Image.java
  src/main/java/com/amcamp/domain/image/domain/ImageFileExtension.java
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadCompleteRequest.java
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadRequest.java
  src/main/java/com/amcamp/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/main/java/com/amcamp/domain/member/domain/Member.java
  src/main/java/com/amcamp/domain/member/dto/.gitkeep
  src/main/java/com/amcamp/domain/member/dto/request/NicknameUpdateRequest.java
  src/main/java/com/amcamp/global/common/constants/UrlConstants.java
  src/main/java/com/amcamp/global/exception/errorcode/ImageErrorCode.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/java/com/amcamp/infra/config/s3/S3Config.java
  src/main/java/com/amcamp/infra/config/s3/S3Properties.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
  src/test/java/com/amcamp/domain/image/application/ImageServiceTest.java
  src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
  test/.gitignore
  test/src/Main.java
  test/src/Person.java
  test/src/Student.java
  test/src/Worker.java
Labels: ✨ feature

#55 chore: Validation 및 Internal Server Error 처리
  src/main/java/com/amcamp/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadCompleteRequest.java
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadRequest.java
  src/main/java/com/amcamp/domain/member/dto/request/NicknameUpdateRequest.java
  src/main/java/com/amcamp/global/exception/ErrorResponse.java
  src/main/java/com/amcamp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/amcamp/global/exception/errorcode/GlobalErrorCode.java
  src/test/java/com/amcamp/global/exception/ExceptionHandlerTest.java
Labels: ⚙️ chore

#59 feat: 회원 정보 조회
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/main/java/com/amcamp/domain/member/dto/response/MemberInfoResponse.java
  src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
Labels: ✨ feature

#58 feat: 로그아웃 구현
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
Labels: ✨ feature

#64 fix: 이미지 API UnexpectedTypeException으로 인한 Validate 수정
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadCompleteRequest.java
  src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadRequest.java
Labels: 🐛 bug/error

#56 feat: project/sprint/task 도메인 추가
  src/main/java/com/amcamp/domain/project/application/.gitkeep
  src/main/java/com/amcamp/domain/project/domain/Project.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipantRole.java
  src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java
  src/main/java/com/amcamp/domain/project/domain/ToDoStatus.java
  src/main/java/com/amcamp/domain/sprint/domain/Sprint.java
  src/main/java/com/amcamp/domain/sprint/domain/SprintContribution.java
  src/main/java/com/amcamp/domain/task/domain/AssignedStatus.java
  src/main/java/com/amcamp/domain/task/domain/Task.java
  src/main/java/com/amcamp/domain/task/domain/TaskDifficulty.java
Labels: ✨ feature

#66 feat: 팀 도메인에 이모지 추가
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/domain/Team.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamEmojiUpdateRequest.java
  src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: ✨ feature

#67 feat: 회원이 참여한 팀 목록 조회
  src/main/java/com/amcamp/domain/team/api/TeamController.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/dao/TeamRepository.java
  src/main/java/com/amcamp/domain/team/dao/TeamRepositoryCustom.java
  src/main/java/com/amcamp/domain/team/dao/TeamRepositoryImpl.java
  src/main/java/com/amcamp/domain/team/domain/Team.java
  src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java
  src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java
  src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
Labels: ✨ feature

#76 test: 테스트 격리
  src/main/java/com/amcamp/domain/participant/dao/ParticipantRepository.java
  src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java
  src/main/java/com/amcamp/domain/team/application/TeamService.java
  src/main/java/com/amcamp/domain/team/dao/TeamParticipantRepository.java
  src/main/java/com/amcamp/domain/team/dao/TeamRepositoryImpl.java
  src/main/java/com/amcamp/domain/team/domain/TeamParticipant.java
  src/main/java/com/amcamp/domain/team/domain/TeamParticipantRole.java
  src/test/java/com/amcamp/DatabaseCleaner.java
  src/test/java/com/amcamp/IntegrationTest.java
  src/test/java/com/amcamp/domain/image/application/ImageServiceTest.java
  src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
  src/test/java/com/amcamp/domain/team/TeamServiceTest.java
  src/test/resources/application-test.yml
Labels: ✅ test

#72 feat: 이미지 삭제 스케줄러 추가
  src/main/java/com/amcamp/domain/image/application/ImageService.java
  src/main/java/com/amcamp/global/config/scheduler/SchedulerConfig.java
  src/main/java/com/amcamp/infra/scheduler/ImageCleanupScheduler.java
Labels: ✨ feature
